module vmd_bridge
contains

subroutine maybe_write_vmd_cube_scene(cubefile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=200) scenefile
logical lopen

if (ivmdscene==0.and.ivmdrun==0) return

call open_vmd_scene_file(scenefile,lopen)
if (.not.lopen) return
call write_vmd_cube_scene(99,cubefile,isovalue,scenefile)
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine maybe_write_vmd_cube_scene_list(cubefiles,nfile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: nfile
character(len=*),intent(in) :: cubefiles(nfile)
real*8,intent(in) :: isovalue
character(len=200) scenefile
logical lopen

if (ivmdscene==0.and.ivmdrun==0) return
if (nfile<=0) return

call open_vmd_scene_file(scenefile,lopen)
if (.not.lopen) return
call write_vmd_scene_header(99,scenefile)
do ifile=1,nfile
    call write_vmd_cube_molecule(99,cubefiles(ifile),isovalue)
end do
call write_vmd_scene_footer(99)
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine maybe_write_vmd_cube_dataset_scene(cubefile,ndataset,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ndataset
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=200) scenefile
logical lopen

if (ivmdscene==0.and.ivmdrun==0) return
if (ndataset<=0) return

call open_vmd_scene_file(scenefile,lopen)
if (.not.lopen) return
call write_vmd_scene_header(99,scenefile)
call write_vmd_cube_dataset_molecule(99,cubefile,ndataset,isovalue)
call write_vmd_scene_footer(99)
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine write_vmd_cube_scene(ifileid,cubefile,isovalue,scenefile)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid
character(len=*),intent(in) :: cubefile,scenefile
real*8,intent(in) :: isovalue

call write_vmd_scene_header(ifileid,scenefile)
call write_vmd_cube_molecule(ifileid,cubefile,isovalue)
call write_vmd_scene_footer(ifileid)

end subroutine


subroutine open_vmd_scene_file(scenefile,lopen)
use defvar
implicit real*8 (a-h,o-z)
character(len=200),intent(out) :: scenefile
logical,intent(out) :: lopen
integer iopen

scenefile=vmdscenefile
if (scenefile==" ") scenefile="multiwfn_scene.tcl"

open(99,file=scenefile,status="replace",iostat=iopen)
if (iopen/=0) then
    write(*,"(' VMD scene script was not written because the file could not be opened: ',a)") trim(scenefile)
    write(*,"(' VMD scene open IOSTAT = ',i0)") iopen
    lopen=.false.
    return
end if

lopen=.true.

end subroutine


subroutine write_vmd_scene_header(ifileid,scenefile)
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid
character(len=*),intent(in) :: scenefile

write(ifileid,"(a)") "# VMD scene generated by Multiwfn"
write(ifileid,"(a)") "# Load this script in VMD by: source "//trim(scenefile)

end subroutine


subroutine write_vmd_scene_footer(ifileid)
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid

write(ifileid,"(a)") "display projection Orthographic"
write(ifileid,"(a)") "axes location Off"
write(ifileid,"(a)") "display resetview"

end subroutine


subroutine write_vmd_cube_molecule(ifileid,cubefile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=80) c80tmp
character(len=600) c600cube

write(c80tmp,"(f16.8)") abs(isovalue)
c80tmp=adjustl(c80tmp)
c600cube=vmd_tcl_dquote(cubefile)

write(ifileid,"(a)") ""
write(ifileid,"(a)") "# Cube file: "//trim(cubefile)
write(ifileid,"(a)") "# Volumetric dataset index: 0"
write(ifileid,"(a)") "mol new "//trim(c600cube)//" type cube waitfor all"
write(ifileid,"(a)") "mol delrep 0 top"
write(ifileid,"(a)") "mol representation CPK 1.000000 0.300000 16 16"
write(ifileid,"(a)") "mol color Element"
write(ifileid,"(a)") "mol material Opaque"
write(ifileid,"(a)") "mol addrep top"
write(ifileid,"(a)") "mol representation Isosurface "//trim(c80tmp)//" 0 0 0 1 1"
write(ifileid,"(a)") "mol color ColorID 0"
write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
write(ifileid,"(a)") "mol addrep top"
if (isosurshowboth==1) then
    write(ifileid,"(a)") "mol representation Isosurface -"//trim(c80tmp)//" 0 0 0 1 1"
    write(ifileid,"(a)") "mol color ColorID 1"
    write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
    write(ifileid,"(a)") "mol addrep top"
end if

end subroutine


subroutine write_vmd_cube_dataset_molecule(ifileid,cubefile,ndataset,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid,ndataset
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=80) c80tmp,c80idx,c80color
character(len=600) c600cube

write(c80tmp,"(f16.8)") abs(isovalue)
c80tmp=adjustl(c80tmp)
c600cube=vmd_tcl_dquote(cubefile)

write(ifileid,"(a)") ""
write(ifileid,"(a)") "# Multi-dataset cube file: "//trim(cubefile)
write(ifileid,"(a,i0)") "# Number of volumetric datasets: ",ndataset
write(ifileid,"(a)") "mol new "//trim(c600cube)//" type cube waitfor all"
write(ifileid,"(a)") "mol delrep 0 top"
write(ifileid,"(a)") "mol representation CPK 1.000000 0.300000 16 16"
write(ifileid,"(a)") "mol color Element"
write(ifileid,"(a)") "mol material Opaque"
write(ifileid,"(a)") "mol addrep top"
do idataset=1,ndataset
    write(c80idx,"(i10)") idataset-1
    c80idx=adjustl(c80idx)
    write(c80color,"(i10)") mod(2*(idataset-1),32)
    c80color=adjustl(c80color)
    write(ifileid,"(a,i0,a,a)") "# Dataset ",idataset,", VMD volume index ",trim(c80idx)
    write(ifileid,"(a)") "mol representation Isosurface "//trim(c80tmp)//" "//trim(c80idx)//" 0 0 1 1"
    write(ifileid,"(a)") "mol color ColorID "//trim(c80color)
    write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
    write(ifileid,"(a)") "mol addrep top"
    if (isosurshowboth==1) then
        write(c80color,"(i10)") mod(2*(idataset-1)+1,32)
        c80color=adjustl(c80color)
        write(ifileid,"(a)") "mol representation Isosurface -"//trim(c80tmp)//" "//trim(c80idx)//" 0 0 1 1"
        write(ifileid,"(a)") "mol color ColorID "//trim(c80color)
        write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
        write(ifileid,"(a)") "mol addrep top"
    end if
end do

end subroutine


subroutine run_vmd_scene(scenefile)
use defvar
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: scenefile
character(len=600) command

if (vmdpath==" ".or.vmdpath=="none") then
    write(*,"(a)") " VMD was not launched because vmdpath is empty or none"
    return
end if

command=""""//trim(vmdpath)//""" -e """//trim(scenefile)//""""
write(*,"(a)") " Running: "//trim(command)
if (isys==1) then
    call execute_command_line(""""//trim(command)//"""")
else
    call execute_command_line(trim(command))
end if

end subroutine


function vmd_tcl_dquote(text) result(quoted)
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: text
character(len=600) :: quoted
character(len=1) :: ch

quoted=" "
quoted(1:1)=""""
ipos=2
do itxt=1,len_trim(text)
    ch=text(itxt:itxt)
    if (ch=="\".or.ch=="""".or.ch=="$".or.ch=="[".or.ch=="]") then
        if (ipos+1>len(quoted)) exit
        quoted(ipos:ipos)="\"
        quoted(ipos+1:ipos+1)=ch
        ipos=ipos+2
    else
        if (ipos>len(quoted)) exit
        quoted(ipos:ipos)=ch
        ipos=ipos+1
    end if
end do
if (ipos<=len(quoted)) quoted(ipos:ipos)=""""

end function

end module
