module vmd_bridge
contains

subroutine maybe_write_vmd_cube_scene(cubefile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=200) scenefile

if (ivmdscene==0.and.ivmdrun==0) return

scenefile=vmdscenefile
if (scenefile==" ") scenefile="multiwfn_scene.tcl"

open(99,file=scenefile,status="replace")
call write_vmd_cube_scene(99,cubefile,isovalue,scenefile)
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine maybe_write_vmd_cube_scene_list(cubefiles,nfile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: nfile
character(len=*),intent(in) :: cubefiles(nfile)
real*8,intent(in) :: isovalue
character(len=200) scenefile

if (ivmdscene==0.and.ivmdrun==0) return
if (nfile<=0) return

scenefile=vmdscenefile
if (scenefile==" ") scenefile="multiwfn_scene.tcl"

open(99,file=scenefile,status="replace")
write(99,"(a)") "# VMD scene generated by Multiwfn"
write(99,"(a)") "# Load this script in VMD by: source "//trim(scenefile)
do ifile=1,nfile
    call write_vmd_cube_molecule(99,cubefiles(ifile),isovalue)
end do
write(99,"(a)") "display projection Orthographic"
write(99,"(a)") "axes location Off"
write(99,"(a)") "display resetview"
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine maybe_write_vmd_cube_dataset_scene(cubefile,ndataset,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ndataset
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=200) scenefile

if (ivmdscene==0.and.ivmdrun==0) return
if (ndataset<=0) return

scenefile=vmdscenefile
if (scenefile==" ") scenefile="multiwfn_scene.tcl"

open(99,file=scenefile,status="replace")
write(99,"(a)") "# VMD scene generated by Multiwfn"
write(99,"(a)") "# Load this script in VMD by: source "//trim(scenefile)
call write_vmd_cube_dataset_molecule(99,cubefile,ndataset,isovalue)
write(99,"(a)") "display projection Orthographic"
write(99,"(a)") "axes location Off"
write(99,"(a)") "display resetview"
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine write_vmd_cube_scene(ifileid,cubefile,isovalue,scenefile)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid
character(len=*),intent(in) :: cubefile,scenefile
real*8,intent(in) :: isovalue

write(ifileid,"(a)") "# VMD scene generated by Multiwfn"
write(ifileid,"(a)") "# Load this script in VMD by: source "//trim(scenefile)
call write_vmd_cube_molecule(ifileid,cubefile,isovalue)
write(ifileid,"(a)") "display projection Orthographic"
write(ifileid,"(a)") "axes location Off"
write(ifileid,"(a)") "display resetview"

end subroutine


subroutine write_vmd_cube_molecule(ifileid,cubefile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=80) c80tmp

write(c80tmp,"(f16.8)") abs(isovalue)
c80tmp=adjustl(c80tmp)

write(ifileid,"(a)") "mol new {"//trim(cubefile)//"} type cube waitfor all"
write(ifileid,"(a)") "mol delrep 0 top"
write(ifileid,"(a)") "mol representation CPK 1.000000 0.300000 16 16"
write(ifileid,"(a)") "mol color Element"
write(ifileid,"(a)") "mol material Opaque"
write(ifileid,"(a)") "mol addrep top"
write(ifileid,"(a)") "mol representation Isosurface "//trim(c80tmp)//" 0 0 0 1 1"
write(ifileid,"(a)") "mol color ColorID 0"
write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
write(ifileid,"(a)") "mol addrep top"
if (isosurshowboth==1) then
    write(ifileid,"(a)") "mol representation Isosurface -"//trim(c80tmp)//" 0 0 0 1 1"
    write(ifileid,"(a)") "mol color ColorID 1"
    write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
    write(ifileid,"(a)") "mol addrep top"
end if

end subroutine


subroutine write_vmd_cube_dataset_molecule(ifileid,cubefile,ndataset,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid,ndataset
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=80) c80tmp,c80idx,c80color

write(c80tmp,"(f16.8)") abs(isovalue)
c80tmp=adjustl(c80tmp)

write(ifileid,"(a)") "mol new {"//trim(cubefile)//"} type cube waitfor all"
write(ifileid,"(a)") "mol delrep 0 top"
write(ifileid,"(a)") "mol representation CPK 1.000000 0.300000 16 16"
write(ifileid,"(a)") "mol color Element"
write(ifileid,"(a)") "mol material Opaque"
write(ifileid,"(a)") "mol addrep top"
do idataset=1,ndataset
    write(c80idx,"(i10)") idataset-1
    c80idx=adjustl(c80idx)
    write(c80color,"(i10)") mod(2*(idataset-1),32)
    c80color=adjustl(c80color)
    write(ifileid,"(a)") "mol representation Isosurface "//trim(c80tmp)//" "//trim(c80idx)//" 0 0 1 1"
    write(ifileid,"(a)") "mol color ColorID "//trim(c80color)
    write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
    write(ifileid,"(a)") "mol addrep top"
    if (isosurshowboth==1) then
        write(c80color,"(i10)") mod(2*(idataset-1)+1,32)
        c80color=adjustl(c80color)
        write(ifileid,"(a)") "mol representation Isosurface -"//trim(c80tmp)//" "//trim(c80idx)//" 0 0 1 1"
        write(ifileid,"(a)") "mol color ColorID "//trim(c80color)
        write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
        write(ifileid,"(a)") "mol addrep top"
    end if
end do

end subroutine


subroutine run_vmd_scene(scenefile)
use defvar
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: scenefile
character(len=600) command

if (vmdpath==" ".or.vmdpath=="none") then
    write(*,"(a)") " VMD was not launched because vmdpath is empty or none"
    return
end if

command=""""//trim(vmdpath)//""" -e """//trim(scenefile)//""""
write(*,"(a)") " Running: "//trim(command)
if (isys==1) then
    call execute_command_line(""""//trim(command)//"""")
else
    call execute_command_line(trim(command))
end if

end subroutine

end module
