module vmd_bridge
contains

subroutine maybe_write_vmd_cube_scene(cubefile,isovalue)
use defvar
use util
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=200) scenefile

if (ivmdscene==0.and.ivmdrun==0) return

scenefile=vmdscenefile
if (scenefile==" ") scenefile="multiwfn_scene.tcl"

open(99,file=scenefile,status="replace")
call write_vmd_cube_scene(99,cubefile,isovalue)
close(99)

write(*,"(' VMD scene script has been written to ',a)") trim(scenefile)
if (ivmdrun==1) call run_vmd_scene(scenefile)

end subroutine


subroutine write_vmd_cube_scene(ifileid,cubefile,isovalue)
use defvar
implicit real*8 (a-h,o-z)
integer,intent(in) :: ifileid
character(len=*),intent(in) :: cubefile
real*8,intent(in) :: isovalue
character(len=80) c80tmp

write(c80tmp,"(f16.8)") abs(isovalue)
c80tmp=adjustl(c80tmp)

write(ifileid,"(a)") "# VMD scene generated by Multiwfn"
write(ifileid,"(a)") "# Load this script in VMD by: source "//trim(vmdscenefile)
write(ifileid,"(a)") "mol new {"//trim(cubefile)//"} type cube waitfor all"
write(ifileid,"(a)") "mol delrep 0 top"
write(ifileid,"(a)") "mol representation CPK 1.000000 0.300000 16 16"
write(ifileid,"(a)") "mol color Element"
write(ifileid,"(a)") "mol material Opaque"
write(ifileid,"(a)") "mol addrep top"
write(ifileid,"(a)") "mol representation Isosurface "//trim(c80tmp)//" 0 0 0 1 1"
write(ifileid,"(a)") "mol color ColorID 0"
write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
write(ifileid,"(a)") "mol addrep top"
if (isosurshowboth==1) then
    write(ifileid,"(a)") "mol representation Isosurface -"//trim(c80tmp)//" 0 0 0 1 1"
    write(ifileid,"(a)") "mol color ColorID 1"
    write(ifileid,"(a)") "mol material "//trim(vmdmaterial)
    write(ifileid,"(a)") "mol addrep top"
end if
write(ifileid,"(a)") "display projection Orthographic"
write(ifileid,"(a)") "axes location Off"
write(ifileid,"(a)") "display resetview"

end subroutine


subroutine run_vmd_scene(scenefile)
use defvar
use util
implicit real*8 (a-h,o-z)
character(len=*),intent(in) :: scenefile
character(len=600) command

if (vmdpath==" ".or.vmdpath=="none") then
    write(*,"(a)") " VMD was not launched because vmdpath is empty or none"
    return
end if

command=""""//trim(vmdpath)//""" -e """//trim(scenefile)//""""
call runcommand(trim(command))

end subroutine

end module
