#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 /path/to/Multiwfn_noGUI" >&2
  exit 2
fi

exe="$1"
if [ ! -x "$exe" ]; then
  echo "Executable is not runnable: $exe" >&2
  exit 2
fi

workdir="$(mktemp -d)"
cleanup() {
  rm -rf "$workdir"
}
trap cleanup EXIT

export OMP_STACKSIZE="${OMP_STACKSIZE:-64000000}"

assert_contains() {
  local file="$1"
  local text="$2"
  if ! grep -Fq "$text" "$file"; then
    echo "Expected to find: $text" >&2
    echo "--- $file tail ---" >&2
    tail -n 120 "$file" >&2 || true
    echo "--- end tail ---" >&2
    exit 1
  fi
}

cat > "$workdir/water.xyz" <<'EOF'
3
water
O 0 0 0
H 0 0 0.96
H 0.92 0 -0.24
EOF

printf '26\n1\n\nq\n0\nq\n' | "$exe" "$workdir/water.xyz" > "$workdir/geometry.out"
assert_contains "$workdir/geometry.out" "water.xyz successfully!"
assert_contains "$workdir/geometry.out" "Formula: H2 O1"
assert_contains "$workdir/geometry.out" "Mass of these atoms:         18.015286 amu"
assert_contains "$workdir/geometry.out" "Geometry center (X/Y/Z):    0.30666667    0.00000000    0.24000000 Angstrom"
assert_contains "$workdir/geometry.out" "Maximum distance is    1.512085 Angstrom"
assert_contains "$workdir/geometry.out" "Minimum distance is    0.950789 Angstrom"

cat > "$workdir/tiny.cub" <<'EOF'
Test cube
Generated for Multiwfn CI
    1    0.000000    0.000000    0.000000
    2    1.000000    0.000000    0.000000
    2    0.000000    1.000000    0.000000
    2    0.000000    0.000000    1.000000
    8    0.000000    0.000000    0.000000    0.000000
  1.000000E-01  2.000000E-01  3.000000E-01  4.000000E-01  5.000000E-01  6.000000E-01
  7.000000E-01  8.000000E-01
EOF

(
  cd "$workdir"
  printf '13\n0\nroundtrip.cub\n-1\nq\n' | "$exe" tiny.cub > grid.out
)
assert_contains "$workdir/grid.out" "Loaded tiny.cub successfully!"
assert_contains "$workdir/grid.out" "Total number of grid points:           8"
assert_contains "$workdir/grid.out" "Global minimum value:  0.10000000E+00"
assert_contains "$workdir/grid.out" "Global maximum value:  0.80000000E+00"
assert_contains "$workdir/grid.out" "Done, cube file has been outputted"
assert_contains "$workdir/roundtrip.cub" "Generated by Multiwfn"
assert_contains "$workdir/roundtrip.cub" "Totally            8 grid points"
assert_contains "$workdir/roundtrip.cub" "1.00000E-001  2.00000E-001"
assert_contains "$workdir/roundtrip.cub" "7.00000E-001  8.00000E-001"

echo "noGUI functional tests passed"
