#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 /path/to/Multiwfn_noGUI" >&2
  exit 2
fi

exe="$1"
if [ ! -x "$exe" ]; then
  echo "Executable is not runnable: $exe" >&2
  exit 2
fi

workdir="$(mktemp -d)"
cleanup() {
  rm -rf "$workdir"
}
trap cleanup EXIT

export OMP_STACKSIZE="${OMP_STACKSIZE:-64000000}"
export OMP_THREAD_LIMIT=1

assert_contains() {
  local file="$1"
  local text="$2"
  if ! grep -Fq -- "$text" "$file"; then
    echo "Expected to find: $text" >&2
    echo "--- $file tail ---" >&2
    tail -n 120 "$file" >&2 || true
    echo "--- end tail ---" >&2
    exit 1
  fi
}

cat > "$workdir/water.xyz" <<'EOF'
3
water
O 0 0 0
H 0 0 0.96
H 0.92 0 -0.24
EOF

printf '26\n1\n\nq\n0\nq\n' | "$exe" "$workdir/water.xyz" > "$workdir/geometry.out"
assert_contains "$workdir/geometry.out" "water.xyz successfully!"
assert_contains "$workdir/geometry.out" "Formula: H2 O1"
assert_contains "$workdir/geometry.out" "Mass of these atoms:         18.015286 amu"
assert_contains "$workdir/geometry.out" "Geometry center (X/Y/Z):    0.30666667    0.00000000    0.24000000 Angstrom"
assert_contains "$workdir/geometry.out" "Maximum distance is    1.512085 Angstrom"
assert_contains "$workdir/geometry.out" "Minimum distance is    0.950789 Angstrom"

cat > "$workdir/tiny.cub" <<'EOF'
Test cube
Generated for Multiwfn CI
    1    0.000000    0.000000    0.000000
    2    1.000000    0.000000    0.000000
    2    0.000000    1.000000    0.000000
    2    0.000000    0.000000    1.000000
    8    0.000000    0.000000    0.000000    0.000000
  1.000000E-01  2.000000E-01  3.000000E-01  4.000000E-01  5.000000E-01  6.000000E-01
  7.000000E-01  8.000000E-01
EOF

(
  cd "$workdir"
  printf '13\n0\nroundtrip.cub\n-1\nq\n' | "$exe" tiny.cub > grid.out
)
assert_contains "$workdir/grid.out" "Loaded tiny.cub successfully!"
assert_contains "$workdir/grid.out" "Total number of grid points:           8"
assert_contains "$workdir/grid.out" "Global minimum value:  0.10000000E+00"
assert_contains "$workdir/grid.out" "Global maximum value:  0.80000000E+00"
assert_contains "$workdir/grid.out" "Done, cube file has been outputted"
assert_contains "$workdir/roundtrip.cub" "Generated by Multiwfn"
assert_contains "$workdir/roundtrip.cub" "Totally            8 grid points"
assert_contains "$workdir/roundtrip.cub" "1.00000E-001  2.00000E-001"
assert_contains "$workdir/roundtrip.cub" "7.00000E-001  8.00000E-001"

# CP2K 2026.1 writes adjacent 13-column fields: there is no whitespace
# between negative values, so free-format input cannot read this valid cube.
head -n 7 "$workdir/tiny.cub" > "$workdir/cp2k.cub"
cat >> "$workdir/cp2k.cub" <<'EOF'
-0.10000E-001-0.20000E-001-0.30000E-001-0.40000E-001-0.50000E-001-0.60000E-001
-0.70000E-001-0.80000E-001
EOF
(
  cd "$workdir"
  printf '13\n0\ncp2k-roundtrip.cub\n-1\nq\n' | "$exe" cp2k.cub > cp2k.out
)
assert_contains "$workdir/cp2k.out" "trying loading using 6E13.5E3"
assert_contains "$workdir/cp2k-roundtrip.cub" "-1.00000E-002 -2.00000E-002"
assert_contains "$workdir/cp2k-roundtrip.cub" "-7.00000E-002 -8.00000E-002"

# Loading an external grid through 1000 -> 19 must not replace water with
# the oxygen-only structure in the cube. Check the subsequent analysis.
(
  cd "$workdir"
  printf '1000\n19\ntiny.cub\n26\n1\n\nq\n0\nq\n' | "$exe" water.xyz > grid-only.out
)
assert_contains "$workdir/grid-only.out" "Grid date has been successfully loaded!"
assert_contains "$workdir/grid-only.out" "Formula: H2 O1"
assert_contains "$workdir/grid-only.out" "Geometry center (X/Y/Z):    0.30666667    0.00000000    0.24000000 Angstrom"

# Exercise both new paths together: the fallback must skip the cube's one
# atom record, not the three atoms retained in the current water structure.
(
  cd "$workdir"
  printf '1000\n19\ncp2k.cub\n13\n0\ncp2k-grid-only.cub\n-1\n26\n1\n\nq\n0\nq\n' | "$exe" water.xyz > cp2k-grid-only.out
)
assert_contains "$workdir/cp2k-grid-only.out" "Grid date has been successfully loaded!"
assert_contains "$workdir/cp2k-grid-only.out" "Formula: H2 O1"
assert_contains "$workdir/cp2k-grid-only.cub" "-1.00000E-002 -2.00000E-002"
assert_contains "$workdir/cp2k-grid-only.cub" "-7.00000E-002 -8.00000E-002"

# CP2K Molden files may declare the cell in Bohr and valence nuclear charges.
# Both cell encodings must retain their dimensions, without a second conversion.
for cell_format in parameters vectors; do
  {
    printf '[Molden Format]\n[Cell] AU\n'
    if [ "$cell_format" = parameters ]; then
      printf '10 12 14 90 90 90\n'
    else
      printf '%s\n' 'A 10 0 0' 'B 0 12 0' 'C 0 0 14'
    fi
    cat <<'EOF'
[Atoms] AU
C 1 6 0 0 0
[Pseudo]
C 1 4
[GTO]
1 0
s 1 1.0
1.0 1.0

[MO]
Sym= A1
Ene= -0.5
Spin= Alpha
Occup= 2.0
1 1.0
EOF
  } > "$workdir/cell-$cell_format.molden"
  printf 'q\n' | "$exe" "$workdir/cell-$cell_format.molden" > "$workdir/cell-$cell_format.out"
  assert_contains "$workdir/cell-$cell_format.out" "Nuclear charge of atom     1 has been changed to   4"
  assert_contains "$workdir/cell-$cell_format.out" "Cell vector 1,  X=   10.00000  Y=    0.00000  Z=    0.00000  Norm:   10.00000"
  assert_contains "$workdir/cell-$cell_format.out" "Cell vector 2,  X=    0.00000  Y=   12.00000  Z=    0.00000  Norm:   12.00000"
  assert_contains "$workdir/cell-$cell_format.out" "Cell vector 3,  X=    0.00000  Y=    0.00000  Z=   14.00000  Norm:   14.00000"
done

# Compare the new standard-deviation/TFI export with the established TFI
# calculation for both gradient models. This small trajectory includes an
# interacting grid point and screened zero-density points.
for analysis in 12 -12; do
  case_dir="$workdir/tfi-$analysis"
  mkdir "$case_dir"
  cat > "$case_dir/trajectory.xyz" <<'EOF'
2
frame one
H 0 0 0
H 1 0 0
2
frame two
H 0 0 0
H 1.2 0 0
EOF
  (
    cd "$case_dir"
    printf '20\n%s\n2\n1\n2\n\n5\n0.5,0.5,0.5\n4,4,4\n3,3,3\n6\n8\n0\n0\nq\n' "$analysis" | "$exe" trajectory.xyz > tfi.out
  )
  model=aIGM
  if [ "$analysis" = -12 ]; then model=amIGM; fi
  awk '
    FNR > 8 {
      for (i=1; i<=NF; i++) {
        if (tolower($i) ~ /nan|inf/) exit 1
        if (FILENAME == ARGV[1]) {
          ref[n++]=$i+0
          if ($i+0 == 0) zeros++; else nonzeros++
        } else {
          delta=($i+0)-ref[m]
          if (delta<0) delta=-delta
          scale=ref[m]; if (scale<0) scale=-scale
          if (delta>1e-10+1e-5*scale) exit 1
          m++
        }
      }
    }
    END { if (n!=27 || m!=n || !zeros || !nonzeros) exit 1 }
  ' "$case_dir/TFI-$model.cub" "$case_dir/TFI_$model.cub"
done

echo "noGUI functional tests passed"
