#!/usr/bin/env sh
set -eu

GNU_PREFIX=${GNU_PREFIX:-$(pwd)/.build-env/gnu}
EXE_noGUI=${EXE_noGUI:-Multiwfn_noGUI}
SMOKE_DIR=${SMOKE_DIR:-.build-env/smoke}
SMOKE_XYZ=${SMOKE_XYZ:-$SMOKE_DIR/water.xyz}
SMOKE_CUBE=${SMOKE_CUBE:-$SMOKE_DIR/water-density.cub}
SMOKE_MWFN=${SMOKE_MWFN:-tools/fixtures/he_minimal.mwfn}
SMOKE_OUT=${SMOKE_OUT:-$SMOKE_DIR/gnu-noGUI-smoke.out}
SMOKE_ERR=${SMOKE_ERR:-$SMOKE_DIR/gnu-noGUI-smoke.err}
SMOKE_CUBE_OUT=${SMOKE_CUBE_OUT:-$SMOKE_DIR/gnu-noGUI-cube-smoke.out}
SMOKE_CUBE_ERR=${SMOKE_CUBE_ERR:-$SMOKE_DIR/gnu-noGUI-cube-smoke.err}
SMOKE_MWFN_OUT=${SMOKE_MWFN_OUT:-$SMOKE_DIR/gnu-noGUI-mwfn-point-smoke.out}
SMOKE_MWFN_ERR=${SMOKE_MWFN_ERR:-$SMOKE_DIR/gnu-noGUI-mwfn-point-smoke.err}
SMOKE_MULLIKEN_OUT=${SMOKE_MULLIKEN_OUT:-$SMOKE_DIR/gnu-noGUI-mwfn-mulliken-smoke.out}
SMOKE_MULLIKEN_ERR=${SMOKE_MULLIKEN_ERR:-$SMOKE_DIR/gnu-noGUI-mwfn-mulliken-smoke.err}
SMOKE_VMD_DIR=${SMOKE_VMD_DIR:-$SMOKE_DIR/vmd-export}
SMOKE_VMD_EXPORT_XYZ=${SMOKE_VMD_EXPORT_XYZ:-$SMOKE_VMD_DIR/exported.xyz}
SMOKE_VMD_SCENE=${SMOKE_VMD_SCENE:-$SMOKE_VMD_EXPORT_XYZ.vmd.tcl}
SMOKE_VMD_OUT=${SMOKE_VMD_OUT:-$SMOKE_VMD_DIR/gnu-noGUI-vmd-structure-smoke.out}
SMOKE_VMD_ERR=${SMOKE_VMD_ERR:-$SMOKE_VMD_DIR/gnu-noGUI-vmd-structure-smoke.err}
SMOKE_VMD_CUBE_DIR=${SMOKE_VMD_CUBE_DIR:-$SMOKE_DIR/vmd-cube-export}
SMOKE_VMD_EXPORT_CUBE=${SMOKE_VMD_EXPORT_CUBE:-$SMOKE_VMD_CUBE_DIR/exported.cub}
SMOKE_VMD_CUBE_SCENE=${SMOKE_VMD_CUBE_SCENE:-$SMOKE_VMD_EXPORT_CUBE.vmd.tcl}
SMOKE_VMD_CUBE_OUT=${SMOKE_VMD_CUBE_OUT:-$SMOKE_VMD_CUBE_DIR/gnu-noGUI-vmd-cube-smoke.out}
SMOKE_VMD_CUBE_ERR=${SMOKE_VMD_CUBE_ERR:-$SMOKE_VMD_CUBE_DIR/gnu-noGUI-vmd-cube-smoke.err}

allowed_stderr='Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG'

run_multiwfn() {
    lib_path=$GNU_PREFIX/lib
    if [ "${LD_LIBRARY_PATH:-}" ]; then
        lib_path=$lib_path:$LD_LIBRARY_PATH
    fi
    LD_LIBRARY_PATH=$lib_path timeout 12s "./$EXE_noGUI" "$@"
}

check_stderr() {
    errfile=$1
    label=$2
    if [ -s "$errfile" ] && grep -Fvx "$allowed_stderr" "$errfile" >/dev/null; then
        printf '%s\n' "Unexpected $label stderr:"
        cat "$errfile"
        exit 1
    fi
}

restore_settings() {
    if [ -f "$SMOKE_DIR/settings.ini.before" ]; then
        cp "$SMOKE_DIR/settings.ini.before" settings.ini
    fi
}

mkdir -p "$SMOKE_DIR" "$SMOKE_VMD_DIR" "$SMOKE_VMD_CUBE_DIR"

printf '%s\n%s\n%s\n%s\n%s\n' \
    '3' \
    'water smoke test' \
    'O 0.000000 0.000000 0.000000' \
    'H 0.758602 0.000000 0.504284' \
    'H -0.758602 0.000000 0.504284' > "$SMOKE_XYZ"

printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' \
    'Water density smoke test' \
    'Generated by gnu-noGUI-smoke' \
    '    3    0.000000    0.000000    0.000000' \
    '    2    0.500000    0.000000    0.000000' \
    '    2    0.000000    0.500000    0.000000' \
    '    2    0.000000    0.000000    0.500000' \
    '    8    0.000000    0.000000    0.000000    0.000000' \
    '    1    0.000000    0.758602    0.000000    0.504284' \
    '    1    0.000000   -0.758602    0.000000    0.504284' > "$SMOKE_CUBE"
printf '%s\n%s\n' \
    '  0.120000E+00  0.080000E+00  0.080000E+00  0.040000E+00  0.080000E+00  0.040000E+00' \
    '  0.040000E+00  0.020000E+00' >> "$SMOKE_CUBE"

cp settings.ini "$SMOKE_DIR/settings.ini.before"
trap restore_settings EXIT HUP INT TERM

printf '%s\nq\n' "$SMOKE_XYZ" | run_multiwfn > "$SMOKE_OUT" 2> "$SMOKE_ERR"
grep -q 'Loaded .*water.xyz successfully' "$SMOKE_OUT"
grep -q 'Main function menu' "$SMOKE_OUT"
check_stderr "$SMOKE_ERR" "GNU noGUI XYZ smoke"

printf '%s\n%s\n%s\n' 'xyz' "$SMOKE_VMD_EXPORT_XYZ" 'q' |
    run_multiwfn "$SMOKE_XYZ" -vmdrun -vmdpath none -vmdscene auto > "$SMOKE_VMD_OUT" 2> "$SMOKE_VMD_ERR"
grep -q 'Loaded .*water.xyz successfully' "$SMOKE_VMD_OUT"
grep -q 'Exporting xyz file finished!' "$SMOKE_VMD_OUT"
grep -q 'VMD scene script has been written to .*exported.xyz.vmd.tcl' "$SMOKE_VMD_OUT"
grep -q 'VMD was not launched because vmdpath is empty or none' "$SMOKE_VMD_OUT"
test -s "$SMOKE_VMD_EXPORT_XYZ"
test -s "$SMOKE_VMD_SCENE"
grep -Fq "# Structure file: $SMOKE_VMD_EXPORT_XYZ" "$SMOKE_VMD_SCENE"
grep -Fq 'mol new [multiwfn_resolve_path "exported.xyz"] type "xyz" waitfor all' "$SMOKE_VMD_SCENE"
grep -Fq 'mol color Element' "$SMOKE_VMD_SCENE"
tools/vmd-scene-source-check.sh "$SMOKE_VMD_SCENE"
check_stderr "$SMOKE_VMD_ERR" "GNU noGUI VMD structure export smoke"

printf '%s\nq\n' "$SMOKE_CUBE" | run_multiwfn > "$SMOKE_CUBE_OUT" 2> "$SMOKE_CUBE_ERR"
grep -q 'Loaded .*water-density.cub successfully' "$SMOKE_CUBE_OUT"
grep -q 'Main function menu' "$SMOKE_CUBE_OUT"
check_stderr "$SMOKE_CUBE_ERR" "GNU noGUI cube smoke"

printf '%s\n%s\n%s\n%s\n%s\n' '13' '0' "$SMOKE_VMD_EXPORT_CUBE" '-1' 'q' |
    run_multiwfn "$SMOKE_CUBE" -vmdrun -vmdpath none -vmdscene auto > "$SMOKE_VMD_CUBE_OUT" 2> "$SMOKE_VMD_CUBE_ERR"
grep -q 'Loaded .*water-density.cub successfully' "$SMOKE_VMD_CUBE_OUT"
grep -q 'Process grid data' "$SMOKE_VMD_CUBE_OUT"
grep -q 'Done, cube file has been outputted' "$SMOKE_VMD_CUBE_OUT"
grep -q 'VMD scene script has been written to .*exported.cub.vmd.tcl' "$SMOKE_VMD_CUBE_OUT"
grep -q 'VMD was not launched because vmdpath is empty or none' "$SMOKE_VMD_CUBE_OUT"
test -s "$SMOKE_VMD_EXPORT_CUBE"
test -s "$SMOKE_VMD_CUBE_SCENE"
grep -Fq "# Cube file: $SMOKE_VMD_EXPORT_CUBE" "$SMOKE_VMD_CUBE_SCENE"
grep -Fq 'mol new [multiwfn_resolve_path "exported.cub"] type cube waitfor all' "$SMOKE_VMD_CUBE_SCENE"
grep -Fq 'mol representation Isosurface 0.05000000 0 0 0 1 1' "$SMOKE_VMD_CUBE_SCENE"
grep -Fq 'mol representation Isosurface -0.05000000 0 0 0 1 1' "$SMOKE_VMD_CUBE_SCENE"
tools/vmd-scene-source-check.sh "$SMOKE_VMD_CUBE_SCENE"
check_stderr "$SMOKE_VMD_CUBE_ERR" "GNU noGUI VMD cube export smoke"

printf '%s\n%s\n%s\n%s\n%s\n%s\n' "$SMOKE_MWFN" '1' '0.2,0.0,0.0' '1' 'q' 'q' |
    run_multiwfn > "$SMOKE_MWFN_OUT" 2> "$SMOKE_MWFN_ERR"
grep -q 'Loaded .*he_minimal.mwfn successfully' "$SMOKE_MWFN_OUT"
grep -q 'Density of all electrons:' "$SMOKE_MWFN_OUT"
grep -q 'Lagrangian kinetic energy G(r):' "$SMOKE_MWFN_OUT"
grep -q 'Wavefunction value for orbital' "$SMOKE_MWFN_OUT"
check_stderr "$SMOKE_MWFN_ERR" "GNU noGUI mwfn point smoke"

printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' "$SMOKE_MWFN" '7' '5' '1' 'n' '0' '0' 'q' |
    run_multiwfn > "$SMOKE_MULLIKEN_OUT" 2> "$SMOKE_MULLIKEN_ERR"
grep -q 'Loaded .*he_minimal.mwfn successfully' "$SMOKE_MULLIKEN_OUT"
grep -q 'Mulliken population analysis' "$SMOKE_MULLIKEN_OUT"
grep -q 'Population of basis functions:' "$SMOKE_MULLIKEN_OUT"
grep -q 'Atom     1(He)    Population:  2.00000000    Net charge:  0.00000000' "$SMOKE_MULLIKEN_OUT"
grep -q 'Total net charge:    0.00000000' "$SMOKE_MULLIKEN_OUT"
check_stderr "$SMOKE_MULLIKEN_ERR" "GNU noGUI mwfn Mulliken smoke"

cat "$SMOKE_ERR"
cat "$SMOKE_VMD_ERR"
cat "$SMOKE_CUBE_ERR"
cat "$SMOKE_VMD_CUBE_ERR"
cat "$SMOKE_MWFN_ERR"
cat "$SMOKE_MULLIKEN_ERR"
